In [29]:
import pandas as pd
import numpy as np

In [30]:
df = pd.read_csv('top10K-TMDB-movies.csv')
df.head()

id                        title                 genre original_language  \
0    278     The Shawshank Redemption           Drama,Crime                en   
1  19404  Dilwale Dulhania Le Jayenge  Comedy,Drama,Romance                hi   
2    238                The Godfather           Drama,Crime                en   
3    424             Schindler's List     Drama,History,War                en   
4    240       The Godfather: Part II           Drama,Crime                en   

                                            overview  popularity release_date  \
0  Framed in the 1940s for the double murder of h...      94.075   1994-09-23   
1  Raj is a rich, carefree, happy-go-lucky second...      25.408   1995-10-19   
2  Spanning the years 1945 to 1955, a chronicle o...      90.585   1972-03-14   
3  The true story of how businessman Oskar Schind...      44.761   1993-12-15   
4  In the continuing saga of the Corleone crime f...      57.749   1974-12-20   

   vote_average  vote_count  
0           8.7       21862  
1           8.7        3731  
2           8.7       16280  
3           8.6       12959  
4           8.6        9811

In [31]:
df.describe()

id    popularity  vote_average    vote_count
count   10000.000000  10000.000000  10000.000000  10000.000000
mean   161243.505000     34.697267      6.621150   1547.309400
std    211422.046043    211.684175      0.766231   2648.295789
min         5.000000      0.600000      4.600000    200.000000
25%     10127.750000      9.154750      6.100000    315.000000
50%     30002.500000     13.637500      6.600000    583.500000
75%    310133.500000     25.651250      7.200000   1460.000000
max    934761.000000  10436.917000      8.700000  31917.000000

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 10000 non-null  int64  
 1   title              10000 non-null  object 
 2   genre              9997 non-null   object 
 3   original_language  10000 non-null  object 
 4   overview           9987 non-null   object 
 5   popularity         10000 non-null  float64
 6   release_date       10000 non-null  object 
 7   vote_average       10000 non-null  float64
 8   vote_count         10000 non-null  int64  
dtypes: float64(2), int64(2), object(5)
memory usage: 703.3+ KB


In [33]:
df.isnull().sum()

id                    0
title                 0
genre                 3
original_language     0
overview             13
popularity            0
release_date          0
vote_average          0
vote_count            0
dtype: int64

In [34]:
columns = df.columns
columns

Index(['id', 'title', 'genre', 'original_language', 'overview', 'popularity',
       'release_date', 'vote_average', 'vote_count'],
      dtype='object')

In [35]:
# Extracting Feature 

# Most Needed 

''' Id , Titile, Genre, Overview '''

movies = df[['id','title','genre','overview']]
movies.head()

id                        title                 genre  \
0    278     The Shawshank Redemption           Drama,Crime   
1  19404  Dilwale Dulhania Le Jayenge  Comedy,Drama,Romance   
2    238                The Godfather           Drama,Crime   
3    424             Schindler's List     Drama,History,War   
4    240       The Godfather: Part II           Drama,Crime   

                                            overview  
0  Framed in the 1940s for the double murder of h...  
1  Raj is a rich, carefree, happy-go-lucky second...  
2  Spanning the years 1945 to 1955, a chronicle o...  
3  The true story of how businessman Oskar Schind...  
4  In the continuing saga of the Corleone crime f...

In [36]:
movies['tags'] = movies['genre'] + movies['overview']
movies.drop(['overview', 'genre'], axis=1)

C:\Users\haris\AppData\Local\Temp\ipykernel_10028\171627252.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'] = movies['genre'] + movies['overview']


id                                          title  \
0        278                       The Shawshank Redemption   
1      19404                    Dilwale Dulhania Le Jayenge   
2        238                                  The Godfather   
3        424                               Schindler's List   
4        240                         The Godfather: Part II   
...      ...                                            ...   
9995   10196                             The Last Airbender   
9996  331446                       Sharknado 3: Oh Hell No!   
9997   13995                                Captain America   
9998    2312  In the Name of the King: A Dungeon Siege Tale   
9999  455957                                         Domino   

                                                   tags  
0     Drama,CrimeFramed in the 1940s for the double ...  
1     Comedy,Drama,RomanceRaj is a rich, carefree, h...  
2     Drama,CrimeSpanning the years 1945 to 1955, a ...  
3     Drama,History,WarThe true story of how busines...  
4     Drama,CrimeIn the continuing saga of the Corle...  
...                                                 ...  
9995  Action,Adventure,FantasyThe story follows the ...  
9996  Action,TV Movie,Science Fiction,Comedy,Adventu...  
9997  Action,Science Fiction,WarDuring World War II,...  
9998  Adventure,Fantasy,Action,DramaA man named Farm...  
9999  Thriller,Action,CrimeSeeking justice for his p...  

[10000 rows x 3 columns]

**CountVectorizer** (Just Counts the words) :  It converts a collection of text documents into a matrix of token counts, representing the frequency of words (or tokens) in each document.

**[*CountVectorizer*]** processes text by:

**Tokenization**: Splitting text into individual words or tokens (by default, words are split based on whitespace and punctuation is ignored).



**Vocabulary Building**: Creating a vocabulary of unique tokens (words) from the entire corpus (collection of documents).



**Counting**: Counting the frequency of each token in each document.


**Matrix Creation**: Representing the corpus as a sparse matrix where rows correspond to documents and columns correspond to tokens in the vocabulary. Each cell contains the count of a token in a document.

Works:


documents = [
    "I love to code",
    "Code is fun",
    "I love to learn"
]


----------------------------


Output:
[[1 0 0 0 1 1]  # "I love to code"

[1 1 1 0 0 0]  # "Code is fun"

[0 0 0 1 1 1]] # "I love to learn"


-------------------------------


where 
columns : I Love to Code fun learn    {Unique Text (Words like in Dictonaries)}

Rows:  Takes the presence of word from the text  {It shows 1 in the place of word in the dictonarie}

In [37]:
from sklearn.feature_extraction.text import CountVectorizer

In [38]:
Cv  =  CountVectorizer(max_features=(10000),stop_words='english') # removes stop words (, . @ ``) in english language and Max_Feature is Rows (uniuqe data and need all)
Cv

CountVectorizer(max_features=10000, stop_words='english')

Cv.fit_transform returns a sparse matrix (in CSR format) to save memory, as most cells are zeros (most words don’t appear in most documents).

This Doesn't Work (processed = Cv.fit_transform(movies['tags'].values)):



Because the values is mxed of types making it string only helps CountVector Work

In [39]:
processed = Cv.fit_transform(movies['tags'].values.astype('U'))

**astype('U')** : Non-string data (e.g., integers, floats) is converted to their string representation (e.g., 1 becomes '1', 3.14 becomes '3.14').

In [40]:
processed = processed.toarray()

In [41]:
processed.shape

(10000, 10000)

In [42]:
processed

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(10000, 10000))

In [43]:
from sklearn.metrics.pairwise import cosine_similarity

In [44]:
similairty = cosine_similarity(processed)

In [45]:
similairty

array([[1.        , 0.06253054, 0.05802589, ..., 0.07963978, 0.07597372,
        0.03798686],
       [0.06253054, 1.        , 0.08980265, ..., 0.        , 0.        ,
        0.        ],
       [0.05802589, 0.08980265, 1.        , ..., 0.02541643, 0.03636965,
        0.        ],
       ...,
       [0.07963978, 0.        , 0.02541643, ..., 1.        , 0.03327792,
        0.03327792],
       [0.07597372, 0.        , 0.03636965, ..., 0.03327792, 1.        ,
        0.04761905],
       [0.03798686, 0.        , 0.        , ..., 0.03327792, 0.04761905,
        1.        ]], shape=(10000, 10000))

We want to make Similairty as a dictonaries with index value of movie rows and inside another(0 to end , scores for each relation )

In [54]:
name = str(input('Movie Name'))

movies_index = movies[movies['title']==name].index[0] # Gets orignal index of the movie

# index gives [Index([2], dtype='int64')] need only that (2) in the first index

int(movies_index)


2

Syntax: lambda x: x[1] is a lambda function that:


Takes an input x (each item in the iterable being sorted).


Returns x[1], the second element of x.

In [61]:
distance  = sorted(enumerate(similairty[int(movies_index)]), reverse=True , key=lambda x:x[1])
distance


[(2, np.float64(1.0000000000000002)),
 (4, np.float64(0.41247895569215265)),
 (2412, np.float64(0.28867513459481287)),
 (4569, np.float64(0.28426762180748055)),
 (9520, np.float64(0.27801921874276636)),
 (7049, np.float64(0.2773500981126146)),
 (1816, np.float64(0.27036903521793754)),
 (6964, np.float64(0.26461887337857853)),
 (4872, np.float64(0.26352313834736496)),
 (747, np.float64(0.25724787771376323)),
 (734, np.float64(0.251259453814803)),
 (2272, np.float64(0.251259453814803)),
 (330, np.float64(0.24999999999999997)),
 (519, np.float64(0.24999999999999997)),
 (8555, np.float64(0.24326681639992057)),
 (892, np.float64(0.24283093212859136)),
 (779, np.float64(0.2405626121623441)),
 (7419, np.float64(0.2405626121623441)),
 (8341, np.float64(0.23947373603569988)),
 (951, np.float64(0.2381448361039201)),
 (1120, np.float64(0.23570226039551584)),
 (6587, np.float64(0.23570226039551584)),
 (1447, np.float64(0.2357022603955158)),
 (153, np.float64(0.2333333333333333)),
 (7910, np.float6

In [62]:

top_5 = distance[0:5]
top_5

[(2, np.float64(1.0000000000000002)),
 (4, np.float64(0.41247895569215265)),
 (2412, np.float64(0.28867513459481287)),
 (4569, np.float64(0.28426762180748055)),
 (9520, np.float64(0.27801921874276636))]

In [63]:
# To get the names of the movie

for i in top_5:
    print(movies.iloc[i[0]].title)   # i is (2, np.float64(1.0000000000000002) and i[0] gets first index of it

The Godfather
The Godfather: Part II
Felon
House of Gucci
Gotti


In [64]:
def Recommend(name):
    movies_index = movies[movies['title']==name].index[0]
    distance  = sorted(enumerate(similairty[int(movies_index)]), reverse=True , key=lambda x:x[1])
    for i in distance[0:5]:
        print(movies.iloc[i[0]].title) 

In [65]:
import pickle


In [66]:
pickle.dump(movies,open('movies_list.pkl','wb'))
pickle.dump(similairty,open('Similairty.pkl','wb'))

In [67]:
pickle.load(open('movies_list.pkl','rb'))

id                                          title  \
0        278                       The Shawshank Redemption   
1      19404                    Dilwale Dulhania Le Jayenge   
2        238                                  The Godfather   
3        424                               Schindler's List   
4        240                         The Godfather: Part II   
...      ...                                            ...   
9995   10196                             The Last Airbender   
9996  331446                       Sharknado 3: Oh Hell No!   
9997   13995                                Captain America   
9998    2312  In the Name of the King: A Dungeon Siege Tale   
9999  455957                                         Domino   

                                                 genre  \
0                                          Drama,Crime   
1                                 Comedy,Drama,Romance   
2                                          Drama,Crime   
3                                    Drama,History,War   
4                                          Drama,Crime   
...                                                ...   
9995                          Action,Adventure,Fantasy   
9996  Action,TV Movie,Science Fiction,Comedy,Adventure   
9997                        Action,Science Fiction,War   
9998                    Adventure,Fantasy,Action,Drama   
9999                             Thriller,Action,Crime   

                                               overview  \
0     Framed in the 1940s for the double murder of h...   
1     Raj is a rich, carefree, happy-go-lucky second...   
2     Spanning the years 1945 to 1955, a chronicle o...   
3     The true story of how businessman Oskar Schind...   
4     In the continuing saga of the Corleone crime f...   
...                                                 ...   
9995  The story follows the adventures of Aang, a yo...   
9996  The sharks take bite out of the East Coast whe...   
9997  During World War II, a brave, patriotic Americ...   
9998  A man named Farmer sets out to rescue his kidn...   
9999  Seeking justice for his partner’s murder by an...   

                                                   tags  
0     Drama,CrimeFramed in the 1940s for the double ...  
1     Comedy,Drama,RomanceRaj is a rich, carefree, h...  
2     Drama,CrimeSpanning the years 1945 to 1955, a ...  
3     Drama,History,WarThe true story of how busines...  
4     Drama,CrimeIn the continuing saga of the Corle...  
...                                                 ...  
9995  Action,Adventure,FantasyThe story follows the ...  
9996  Action,TV Movie,Science Fiction,Comedy,Adventu...  
9997  Action,Science Fiction,WarDuring World War II,...  
9998  Adventure,Fantasy,Action,DramaA man named Farm...  
9999  Thriller,Action,CrimeSeeking justice for his p...  

[10000 rows x 5 columns]